import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { copyManagedWeek, deleteManagedShift, getManagedSchedule, ManagedShift, publishManagedSchedule, updateManagedShift } from "@/api";
import { useSession } from "@/session";
import { colors } from "@/theme";

const pad = (v: number) => String(v).padStart(2, "0");
const localDate = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const weekStart = (base = new Date()) => { const d = new Date(base); d.setHours(0, 0, 0, 0); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); return d; };

export default function ManageSchedule() {
  const { data } = useSession();
  const [start, setStart] = useState(weekStart()), [shifts, setShifts] = useState<ManagedShift[]>([]), [editing, setEditing] = useState<ManagedShift | null>(null), [date, setDate] = useState(""), [fromTime, setFromTime] = useState(""), [toTime, setToTime] = useState(""), [employeeId, setEmployeeId] = useState<string | null>(null), [busy, setBusy] = useState(false);
  const end = new Date(start); end.setDate(end.getDate() + 7);
  const load = async () => { setBusy(true); try { setShifts((await getManagedSchedule(start.toISOString(), end.toISOString())).shifts); } catch (reason) { Alert.alert("Nicht möglich", reason instanceof Error ? reason.message : "Bitte erneut versuchen."); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [start]);
  const move = (days: number) => { const next = new Date(start); next.setDate(next.getDate() + days); setStart(next); };
  const open = (shift: ManagedShift) => { const a = new Date(shift.startsAt), b = new Date(shift.endsAt); setEditing(shift); setDate(localDate(a)); setFromTime(`${pad(a.getHours())}:${pad(a.getMinutes())}`); setToTime(`${pad(b.getHours())}:${pad(b.getMinutes())}`); setEmployeeId(shift.assigneeId); };
  const save = async () => { if (!editing) return; setBusy(true); try { await updateManagedShift(editing.id, employeeId, new Date(`${date}T${fromTime}:00`).toISOString(), new Date(`${date}T${toTime}:00`).toISOString()); setEditing(null); await load(); } catch (reason) { Alert.alert("Nicht möglich", reason instanceof Error ? reason.message : "Bitte Angaben prüfen."); } finally { setBusy(false); } };
  const remove = () => editing && Alert.alert("Schicht löschen?", "Diese Aktion kann nicht rückgängig gemacht werden.", [{ text: "Abbrechen", style: "cancel" }, { text: "Löschen", style: "destructive", onPress: async () => { setBusy(true); try { await deleteManagedShift(editing.id); setEditing(null); await load(); } finally { setBusy(false); } } }]);
  const publish = async () => { setBusy(true); try { const result = await publishManagedSchedule(start.toISOString(), end.toISOString()); await load(); Alert.alert("Dienstplan veröffentlicht", `${result.published} Schichten wurden veröffentlicht.`); } catch (reason) { Alert.alert("Nicht möglich", reason instanceof Error ? reason.message : "Bitte erneut versuchen."); } finally { setBusy(false); } };
  const copyWeek = async () => { setBusy(true); try { const result = await copyManagedWeek(start.toISOString(), end.toISOString()); Alert.alert("Woche kopiert", `${result.copied} Schichten wurden als Entwurf in die nächste Woche kopiert.`); } catch (reason) { Alert.alert("Nicht möglich", reason instanceof Error ? reason.message : "Bitte erneut versuchen."); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color={colors.navy} /></Pressable><Text style={styles.title}>Dienstplan verwalten</Text><View style={{ flexDirection: "row", gap: 15 }}><Pressable onPress={copyWeek}><Ionicons name="copy-outline" size={23} color={colors.navy} /></Pressable><Pressable onPress={() => router.push("/manage-shift")}><Ionicons name="add-circle-outline" size={26} color={colors.green} /></Pressable></View></View><View style={styles.week}><Pressable onPress={() => move(-7)}><Ionicons name="chevron-back" size={22} color={colors.navy} /></Pressable><View><Text style={styles.weekTitle}>{start.toLocaleDateString("de-DE", { day: "2-digit", month: "short" })} – {new Date(end.getTime() - 86400000).toLocaleDateString("de-DE", { day: "2-digit", month: "short", year: "numeric" })}</Text><Text style={styles.weekMeta}>{shifts.length} Schichten · {shifts.filter((s) => s.status === "DRAFT").length} Entwürfe</Text></View><Pressable onPress={() => move(7)}><Ionicons name="chevron-forward" size={22} color={colors.navy} /></Pressable></View><ScrollView contentContainerStyle={styles.content}>{shifts.map((shift) => <Pressable key={shift.id} onPress={() => open(shift)} style={styles.shift}><View style={[styles.bar, { backgroundColor: shift.color }]} /><View style={styles.time}><Text style={styles.timeMain}>{new Date(shift.startsAt).toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" })}</Text><Text style={styles.dateText}>{new Date(shift.startsAt).toLocaleDateString("de-DE", { weekday: "short", day: "2-digit", month: "2-digit" })}</Text></View><View style={{ flex: 1 }}><Text style={styles.employee}>{shift.assignee}</Text><Text style={styles.meta}>{shift.position} · {shift.location}</Text></View><View style={[styles.badge, shift.status === "PUBLISHED" ? styles.live : shift.status === "OPEN" ? styles.open : styles.draft]}><Text style={styles.badgeText}>{shift.status}</Text></View></Pressable>)}{!shifts.length && <View style={styles.empty}><Text style={styles.emptyText}>{busy ? "Laden …" : "Keine Schichten in dieser Woche."}</Text></View>}</ScrollView><View style={styles.footer}><Pressable disabled={busy || !shifts.some((s) => s.status === "DRAFT")} onPress={publish} style={[styles.publish, (busy || !shifts.some((s) => s.status === "DRAFT")) && { opacity: .45 }]}><Text style={styles.publishText}>Woche veröffentlichen</Text></Pressable></View>
  <Modal visible={Boolean(editing)} animationType="slide" presentationStyle="pageSheet"><SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={remove}><Ionicons name="trash-outline" size={23} color={colors.danger} /></Pressable><Text style={styles.title}>Schicht bearbeiten</Text><Pressable onPress={() => setEditing(null)}><Ionicons name="close" size={25} color={colors.navy} /></Pressable></View><ScrollView contentContainerStyle={styles.sheet}><Text style={styles.label}>Datum</Text><TextInput value={date} onChangeText={setDate} style={styles.input} /><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.label}>Beginn</Text><TextInput value={fromTime} onChangeText={setFromTime} style={styles.input} /></View><View style={{ flex: 1 }}><Text style={styles.label}>Ende</Text><TextInput value={toTime} onChangeText={setToTime} style={styles.input} /></View></View><Text style={styles.label}>Mitarbeiter</Text><ScrollView horizontal contentContainerStyle={styles.chips} showsHorizontalScrollIndicator={false}><Chip label="OpenShift" selected={!employeeId} onPress={() => setEmployeeId(null)} />{data?.management?.employees.filter((e) => e.isActive).map((e) => <Chip key={e.id} label={e.name} selected={employeeId === e.id} onPress={() => setEmployeeId(e.id)} />)}</ScrollView><Pressable disabled={busy} onPress={save} style={styles.publish}><Text style={styles.publishText}>{busy ? "Speichern …" : "Änderungen speichern"}</Text></Pressable></ScrollView></SafeAreaView></Modal></SafeAreaView>;
}
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, selected && styles.chipActive]}><Text style={[styles.chipText, selected && styles.chipTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { height: 58, paddingHorizontal: 16, backgroundColor: "white", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { color: colors.text, fontSize: 17, fontWeight: "800" }, week: { height: 68, paddingHorizontal: 18, backgroundColor: "white", flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.line }, weekTitle: { color: colors.navy, fontWeight: "800", textAlign: "center" }, weekMeta: { color: colors.muted, fontSize: 10, textAlign: "center", marginTop: 4 }, content: { padding: 12, gap: 8, paddingBottom: 90 }, shift: { minHeight: 70, backgroundColor: "white", borderWidth: 1, borderColor: colors.line, borderRadius: 9, flexDirection: "row", alignItems: "center", overflow: "hidden", gap: 10, paddingRight: 10 }, bar: { width: 5, alignSelf: "stretch" }, time: { width: 67 }, timeMain: { color: colors.navy, fontWeight: "900" }, dateText: { color: colors.muted, fontSize: 9, marginTop: 4 }, employee: { color: colors.text, fontWeight: "800", fontSize: 13 }, meta: { color: colors.muted, fontSize: 10, marginTop: 4 }, badge: { paddingHorizontal: 6, paddingVertical: 4, borderRadius: 8 }, live: { backgroundColor: "#DDF4E9" }, open: { backgroundColor: "#E3EFF8" }, draft: { backgroundColor: "#FFF0D2" }, badgeText: { fontSize: 8, fontWeight: "800", color: colors.text }, empty: { padding: 40, alignItems: "center" }, emptyText: { color: colors.muted }, footer: { position: "absolute", bottom: 0, left: 0, right: 0, padding: 12, backgroundColor: "white", borderTopWidth: 1, borderTopColor: colors.line }, publish: { height: 48, borderRadius: 24, backgroundColor: colors.green, alignItems: "center", justifyContent: "center" }, publishText: { color: "white", fontWeight: "800" }, sheet: { padding: 18 }, label: { color: colors.text, fontSize: 11, fontWeight: "800", marginTop: 14, marginBottom: 7 }, input: { height: 46, borderWidth: 1, borderColor: colors.line, borderRadius: 8, backgroundColor: "white", paddingHorizontal: 12, color: colors.text }, row: { flexDirection: "row", gap: 10 }, chips: { gap: 7, paddingBottom: 24 }, chip: { borderWidth: 1, borderColor: colors.line, borderRadius: 17, paddingHorizontal: 11, paddingVertical: 8, backgroundColor: "white" }, chipActive: { backgroundColor: colors.navy, borderColor: colors.navy }, chipText: { color: colors.text, fontSize: 11, fontWeight: "700" }, chipTextActive: { color: "white" } });
