import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { getManagedTimesheets, ManagedTimesheet, reviewManagedTimesheet } from "@/api";
import { colors } from "@/theme";

const statusLabels: Record<string, string> = { PENDING: "Offen", APPROVED: "Genehmigt", DECLINED: "Abgelehnt" };
const duration = (entry: ManagedTimesheet) => Math.max(0, (new Date(entry.clockOut).getTime() - new Date(entry.clockIn).getTime()) / 3_600_000 - entry.breakMinutes / 60);

export default function TimesheetsScreen() {
  const [entries, setEntries] = useState<ManagedTimesheet[]>([]);
  const [filter, setFilter] = useState<"PENDING" | "ALL">("PENDING");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const load = async () => { try { setEntries((await getManagedTimesheets()).entries); } catch (reason) { Alert.alert("Nicht möglich", reason instanceof Error ? reason.message : "Bitte erneut versuchen."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => filter === "ALL" ? entries : entries.filter((item) => item.approvalStatus === "PENDING"), [entries, filter]);
  const total = visible.reduce((sum, item) => sum + duration(item), 0);
  const review = async (id: string, status: "APPROVED" | "DECLINED") => { setBusy(id); try { await reviewManagedTimesheet(id, status); await load(); } catch (reason) { Alert.alert("Nicht möglich", reason instanceof Error ? reason.message : "Bitte erneut versuchen."); } finally { setBusy(""); } };
  return <SafeAreaView style={styles.safe}>
    <View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color={colors.navy} /></Pressable><Text style={styles.title}>Arbeitszeiten</Text><Pressable onPress={load}><Ionicons name="refresh" size={22} color={colors.green} /></Pressable></View>
    <View style={styles.filters}><Pressable onPress={() => setFilter("PENDING")} style={[styles.filter, filter === "PENDING" && styles.filterActive]}><Text style={[styles.filterText, filter === "PENDING" && styles.filterTextActive]}>Offen ({entries.filter((item) => item.approvalStatus === "PENDING").length})</Text></Pressable><Pressable onPress={() => setFilter("ALL")} style={[styles.filter, filter === "ALL" && styles.filterActive]}><Text style={[styles.filterText, filter === "ALL" && styles.filterTextActive]}>Alle</Text></Pressable><View style={{ flex: 1 }} /><Text style={styles.total}>{total.toFixed(1)} Std.</Text></View>
    <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />} contentContainerStyle={styles.content}>{visible.map((entry) => <View key={entry.id} style={styles.card}><View style={styles.cardTop}><View style={styles.avatar}><Text style={styles.avatarText}>{entry.employee.split(" ").map((item) => item[0]).slice(0, 2).join("")}</Text></View><View style={{ flex: 1 }}><Text style={styles.employee}>{entry.employee}</Text><Text style={styles.date}>{new Date(entry.clockIn).toLocaleDateString("de-DE", { weekday: "short", day: "2-digit", month: "2-digit", year: "numeric" })}</Text></View><View style={[styles.status, entry.approvalStatus === "APPROVED" ? styles.approved : entry.approvalStatus === "DECLINED" ? styles.declined : styles.pending]}><Text style={styles.statusText}>{statusLabels[entry.approvalStatus]}</Text></View></View><View style={styles.metrics}><Metric label="Beginn" value={new Date(entry.clockIn).toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" })} /><Metric label="Ende" value={new Date(entry.clockOut).toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" })} /><Metric label="Pause" value={`${entry.breakMinutes} Min.`} /><Metric label="Netto" value={`${duration(entry).toFixed(2)} Std.`} /></View>{entry.correctionNote && <View style={styles.correction}><Ionicons name="alert-circle-outline" size={18} color="#A46200" /><View style={{ flex: 1 }}><Text style={styles.correctionTitle}>Korrektur angefragt</Text><Text style={styles.correctionText}>{entry.correctionNote}</Text></View></View>}{entry.approvalStatus === "PENDING" && <View style={styles.actions}><Pressable disabled={busy === entry.id} onPress={() => review(entry.id, "DECLINED")} style={[styles.action, styles.reject]}><Text style={styles.rejectText}>Ablehnen</Text></Pressable><Pressable disabled={busy === entry.id} onPress={() => review(entry.id, "APPROVED")} style={[styles.action, styles.accept]}><Text style={styles.acceptText}>{busy === entry.id ? "…" : "Genehmigen"}</Text></Pressable></View>}</View>)}{!visible.length && <View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={48} color={colors.green} /><Text style={styles.emptyTitle}>Alles erledigt</Text><Text style={styles.emptyText}>Keine offenen Arbeitszeiten zur Prüfung.</Text></View>}</ScrollView>
  </SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { height: 58, paddingHorizontal: 16, backgroundColor: "white", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { color: colors.text, fontSize: 18, fontWeight: "800" }, filters: { minHeight: 55, paddingHorizontal: 14, backgroundColor: "white", flexDirection: "row", alignItems: "center", gap: 8, borderBottomWidth: 1, borderBottomColor: colors.line }, filter: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 17, backgroundColor: "#EEF2F4" }, filterActive: { backgroundColor: colors.navy }, filterText: { color: colors.text, fontSize: 11, fontWeight: "700" }, filterTextActive: { color: "white" }, total: { color: colors.navy, fontSize: 12, fontWeight: "800" }, content: { padding: 14, gap: 10, paddingBottom: 40 }, card: { backgroundColor: "white", borderWidth: 1, borderColor: colors.line, borderRadius: 11, padding: 13 }, cardTop: { flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#E5EEF2", alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.navy, fontWeight: "800" }, employee: { color: colors.text, fontSize: 15, fontWeight: "800" }, date: { color: colors.muted, fontSize: 11, marginTop: 3 }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10 }, pending: { backgroundColor: "#FFF1D6" }, approved: { backgroundColor: "#DDF4E9" }, declined: { backgroundColor: "#FBE3E3" }, statusText: { color: colors.text, fontSize: 9, fontWeight: "800" }, metrics: { marginTop: 13, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.line, flexDirection: "row", justifyContent: "space-between" }, metricLabel: { color: colors.muted, fontSize: 9, textTransform: "uppercase" }, metricValue: { color: colors.text, fontSize: 12, fontWeight: "800", marginTop: 3 }, correction: { marginTop: 12, padding: 10, borderRadius: 8, backgroundColor: "#FFF6E5", flexDirection: "row", gap: 8 }, correctionTitle: { color: "#825000", fontSize: 11, fontWeight: "800" }, correctionText: { color: colors.text, fontSize: 12, marginTop: 3 }, actions: { marginTop: 13, flexDirection: "row", gap: 9 }, action: { flex: 1, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" }, reject: { borderWidth: 1, borderColor: colors.danger }, accept: { backgroundColor: colors.green }, rejectText: { color: colors.danger, fontWeight: "800" }, acceptText: { color: "white", fontWeight: "800" }, empty: { alignItems: "center", padding: 40 }, emptyTitle: { color: colors.text, fontSize: 17, fontWeight: "800", marginTop: 10 }, emptyText: { color: colors.muted, fontSize: 13, marginTop: 4 } });
