import { ChevronDown,ChevronLeft,ChevronRight,Copy,Filter,Plus,Printer } from 'lucide-react';
type Shift={time:string;role:string;tone?:'orange'|'purple'|'green'|'open'};
const days=[['Mo','15. Sep'],['Di','16. Sep'],['Mi','17. Sep'],['Do','18. Sep'],['Fr','19. Sep'],['Sa','20. Sep'],['So','21. Sep']];
const people=[
{name:'Sophie Wagner',initials:'SW',role:'Service',hours:'32,0 Std.',shifts:[{time:'09:00 – 17:00',role:'Service · Hauptfiliale'},null,{time:'10:00 – 18:00',role:'Service · Hauptfiliale'},null,{time:'09:00 – 17:00',role:'Service · Hauptfiliale'},null,null]},
{name:'Lukas Becker',initials:'LB',role:'Küche',hours:'24,0 Std.',shifts:[null,{time:'07:00 – 15:00',role:'Küche · Hauptfiliale',tone:'orange'},null,{time:'07:00 – 15:00',role:'Küche · Hauptfiliale',tone:'orange'},null,{time:'08:00 – 16:00',role:'Küche · Hauptfiliale',tone:'orange'},null]},
{name:'Mia Hoffmann',initials:'MH',role:'Teamleitung',hours:'35,5 Std.',shifts:[{time:'08:30 – 16:30',role:'Teamleitung',tone:'purple'},{time:'08:30 – 16:30',role:'Teamleitung',tone:'purple'},null,{time:'11:00 – 19:00',role:'Teamleitung',tone:'purple'},{time:'08:30 – 16:00',role:'Teamleitung',tone:'purple'},null,null]},
{name:'Jonas Fischer',initials:'JF',role:'Verkauf',hours:'16,0 Std.',shifts:[null,null,{time:'12:00 – 20:00',role:'Verkauf · City',tone:'green'},null,null,{time:'10:00 – 18:00',role:'Verkauf · City',tone:'green'},null]}] as const;
const open:Shift[]=[{time:'17:00 – 22:00',role:'Offene Schicht · Service',tone:'open'},{time:'16:00 – 21:00',role:'Offene Schicht · Verkauf',tone:'open'}];
function ShiftCard({shift}:{shift:Shift}){return <div className={`shift ${shift.tone??''}`}><div className="shift-time">{shift.time}</div><div className="shift-role">{shift.role}</div></div>}
export default function SchedulePage(){return <div className="content"><div className="toolbar"><div className="week-control"><button aria-label="Vorherige Woche"><ChevronLeft size={17}/></button><span>15. – 21. September 2026</span><button aria-label="Nächste Woche"><ChevronRight size={17}/></button></div><button className="btn">Heute</button><button className="btn"><Filter size={15}/>Filtern<ChevronDown size={14}/></button><button className="btn"><Copy size={15}/>Woche kopieren</button><span className="toolbar-spacer"/><button className="btn"><Printer size={15}/>Drucken</button><button className="btn primary"><Plus size={16}/>Schicht hinzufügen</button></div><section className="stats"><div className="stat"><div className="stat-label">Geplante Stunden</div><div className="stat-value">107,5</div></div><div className="stat"><div className="stat-label">Lohnkosten</div><div className="stat-value">€ 2.146,50</div></div><div className="stat"><div className="stat-label">Offene Schichten</div><div className="stat-value warning">2</div></div><div className="stat"><div className="stat-label">Unveröffentlicht</div><div className="stat-value">4</div></div></section><div className="schedule-wrap"><div className="schedule"><div className="head">Mitarbeiter</div>{days.map(([d,date],i)=><div className={`head ${i===1?'today':''}`} key={d}><div className="day-name">{d}</div><div className="day-date">{date}</div></div>)}{people.flatMap((person,pi)=>[<div className="employee" key={`${person.name}-name`}><span className="avatar">{person.initials}</span><div><div className="employee-name">{person.name}</div><div className="employee-role">{person.role}</div><div className="hours">{person.hours}</div></div></div>,...person.shifts.map((shift,di)=><div className="cell" key={`${pi}-${di}`}>{shift&&<ShiftCard shift={shift as Shift}/>}<button className="add-shift">+ Schicht</button></div>)])}<div className="employee"><div><div className="employee-name">Offene Schichten</div><div className="employee-role">Für das Team verfügbar</div></div></div>{days.map((_,i)=><div className="cell" key={`open-${i}`}>{i===4&&<ShiftCard shift={open[0]}/>} {i===5&&<ShiftCard shift={open[1]}/>}<button className="add-shift">+ OpenShift</button></div>)}</div></div><div className="legend"><span><i className="dot" style={{background:'#2e8dbf'}}/>Service</span><span><i className="dot" style={{background:'#e58a2d'}}/>Küche</span><span><i className="dot" style={{background:'#8068bd'}}/>Leitung</span><span><i className="dot" style={{background:'#3a9d71'}}/>Verkauf</span></div></div>}
