ALTER TABLE "Location" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "Location" ADD COLUMN "geofenceRadius" INTEGER NOT NULL DEFAULT 150;
ALTER TABLE "TimeEntry" ADD COLUMN "clockInLatitude" DOUBLE PRECISION;
ALTER TABLE "TimeEntry" ADD COLUMN "clockInLongitude" DOUBLE PRECISION;
ALTER TABLE "TimeEntry" ADD COLUMN "clockInAccuracy" DOUBLE PRECISION;
