"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Trash2 } from "lucide-react";
type List = { id: string; name: string; items: string[]; shiftCount: number };
export function TaskListManager({ taskLists }: { taskLists: List[] }) {
  const router = useRouter(), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/task-lists", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), items: String(form.get("items") || "").split("\n").map((x) => x.trim()).filter(Boolean) }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setError(body.error); event.currentTarget.reset(); router.refresh(); }
  async function remove(id: string) { if (!confirm("Diese Aufgabenliste wirklich löschen? Bestehende Schichten verlieren die Verknüpfung.")) return; const response = await fetch(`/api/task-lists/${id}`, { method: "DELETE" }); if (!response.ok) { const body = await response.json(); return setError(body.error); } router.refresh(); }
  return <div className="content"><div className="page-heading"><div><h1>Aufgabenlisten</h1><p>Wiederverwendbare Checklisten für Schichten.</p></div></div>{error && <div className="auth-error">{error}</div>}<div className="team-grid"><form className="invite-form" onSubmit={create}><h2>Neue Aufgabenliste</h2><div className="form-row"><label>Name<input name="name" required maxLength={80} /></label><label>Aufgaben – eine pro Zeile<textarea name="items" required rows={8} placeholder={"Kasse prüfen\nArbeitsbereich reinigen\nÜbergabe dokumentieren"} /></label><button className="btn primary" disabled={busy}>{busy ? "Speichern …" : "Liste speichern"}</button></div></form><div className="employee-list">{taskLists.map((list) => <div className="employee-row" key={list.id}><div style={{ flex: 1 }}><strong>{list.name}</strong><small>{list.items.length} Aufgaben · {list.shiftCount} Schichten</small><div className="task-preview">{list.items.join(" · ")}</div></div><button className="icon-button danger" onClick={() => remove(list.id)}><Trash2 size={16} /></button></div>)}{!taskLists.length && <div className="template-empty">Noch keine Aufgabenlisten.</div>}</div></div></div>;
}
